#pragma once

#include <stdbool.h>

#define TILTYARD_ERROR_CODE_AMOUNT 8
#define TILTYARD_FUNC_AMOUNT 23

#define TILTYARD_ERROR_HANDLING_FUNC_AMOUNT 2
#define TILTYARD_ERROR_HANDLING_CODE_AMOUNT 1

enum tiltyard_error_code {
	EXCEEDED_ARENA_CAPACITY,
	NULL_POINTER_TO_ARENA,
	NOT_ENOUGH_SPACE_FOR_ARENA,
	NOT_ENOUGH_SPACE_FOR_SIZE_OF_ARENA,
	SIZE_EQUALS_ZERO,
	INVALID_ALIGNMENT,
	ALIGNMENT_TOO_BIG,
	OUT_OF_BOUNDS_MARKER,

	TILTYARD_ERROR_HANDLING_ERROR,
};

enum tiltyard_func {
	TILTYARD_CREATE,
	TILTYARD_ALLOC,
	TILTYARD_CALLOC,
	TILTYARD_ALLOC_ALIGNED,
	TILTYARD_CALLOC_ALIGNED,
	TILTYARD_DESTROY,
	TILTYARD_WIPE,
	TILTYARD_NULL,
	TILTYARD_DESTROY_AND_NULL,
	TILTYARD_WIPE_DESTROY_AND_NULL,
	TILTYARD_RESET,
	TILTYARD_GET_MARKER,
	TILTYARD_RESET_TO,
	TILTYARD_CLEAN_UNTIL,
	TILTYARD_CLEAN_FROM,
	TILTYARD_CLEAN_FROM_UNTIL,
	TILTYARD_GET_CAPACITY,
	TILTYARD_GET_USED_CAPACITY,
	TILTYARD_GET_AVAILABLE_CAPACITY,
	TILTYARD_GET_HIGH_WATER,
	TILTYARD_GET_ALLOC_COUNT,
	TILTYARD_GET_LAST_ALLOC,
	TILTYARD_GET_STATS,


	GET_ERROR_CODE_STRING,
	GET_FUNC_STRING,
};

void tiltyard_handle_error(const enum tiltyard_error_code tiltyard_error_code, const enum tiltyard_func in_func, const bool fatal);
